services:
  dev-db:
    container_name: dev-db
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pms-api
    networks:
      - postgres
  pms-api:
    container_name: pms-api
    image: pms-api
    environment:
      # DATABASE_URL: postgresql://postgres:123@dev-db:5432/my-nestjs-app?schema=public
      DATABASE_URL: postgresql://postgres:123@dev-db:5432/pms-api?schema=public
      JWT_SECRET: super-secret
    ports:
      - "3001:3001"
    links:
      - dev-db
    depends_on:
      - dev-db
    networks:
      - postgres
    restart: always
networks:
  postgres:
    driver: bridge